name: Visa-Sponsored-Jobs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6 12 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Fetch job data and generate jobList.json
      run: |
        # Fetch job data directly without authentication
        curl -s https://visajobs.xyz/db.json -o jobList.json
    - name: Fetch latest data
      run: |
        curl https://visajobs.xyz/db.json | jq . > jobList.json

    - name: Parse jobList.json into table
      id: parse-json
      run: |
        cat << EOF > README.md
        # Daily List of Visa-Sponsored Job Opportunities

        Welcome to our repository of daily-updated, visa-sponsored job opportunities! This list is automatically refreshed every day to bring you the latest openings across various companies and locations.


        We encourage the community to engage, share, and support each other in the job search process. If you find this resource helpful, please star the repository and spread the word!

        EOF

        echo "| Company | Job Title | Location | Added | Flag | Link |" >> README.md
        echo "| --- | --- | --- | --- | --- | --- |" >> README.md
        jq -r '.[] | 
          "| " + .company + 
          " | " + .position + 
          " | " + (.location | split(" ")[:-1] | join(" ")) + 
          " | " + .post_date + 
          " | " + (.location | split(" ")[-1]) + 
          " | " + "[Apply](" + .description + ")" + 
          " |"' jobList.json >> README.md

        cat << EOF >> README.md

        ---

        Last updated: $(date -u)

        *Note: This list is automatically updated daily. Check back often for new opportunities!*
        EOF

    - name: Commit and push changes if any
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add README.md

        # Check if there are any changes to commit
        if git diff --cached --quiet; then
          echo "No changes detected. Skipping commit and push."
          exit 0
        fi

        timestamp=$(date -u)
        git commit -m "Latest updated jobs: ${timestamp}"
        git push
