name: Visa-Sponsored Job Listings

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '6 12 * * *'

permissions:
  contents: write  # Allow pushing changes

jobs:
  generate-job-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch Latest Job Data
        run: curl -s https://visajobs.xyz/db.json -o jobList.json

      - name: Parse jobList.json and Update README
        run: |
          cat << EOF > README.md
          # Daily List of Visa-Sponsored Job Opportunities
          | Company | Job Title | Location | Date Posted | Flag | Application Link |
          | --- | --- | --- | --- | --- | --- |
          EOF
          jq -r '.[] | 
            "| " + .company + 
            " | " + .position + 
            " | " + (.location | split(" ")[:-1] | join(" ")) + 
            " | " + .post_date + 
            " | " + (.location | split(" ")[-1]) + 
            " | " + "[Apply](" + .description + ")" + 
            " |"' jobList.json >> README.md
          echo "---\nLast updated: $(date -u)" >> README.md

      - name: Commit and Push Changes (If Any)
        run: |
          git config user.name "Automated Workflow"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
          fi
          git commit -m "Updated job list: $(date -u)"
          git pull --rebase
          git push
